apiVersion: v1
kind: ConfigMap
metadata:
  name: pisethbank-configmap
data:
  SPRING_PROFILES_ACTIVE: default
  SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/"
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eurekaserver:9001/eureka/"
  CONFIGSERVER_APPLICATION_NAME: configserver
  EUREKA_APPLICATION_NAME: eurekaserver
  ACCOUNT_APPLICATION_NAME: account
  LOAN_APPLICATION_NAME: loan
  CARD_APPLICATION_NAME: card
  GATEWAY_APPLICATION_NAME: gatewayserver
  KEYCLOAK_ADMIN: admin
  KEYCLOAK_ADMIN_PASSWORD: admin
  MONGODB_HOST_NAME: mongodb
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK-SET-URI: "http://keycloak:9080/realms/master/protocol/openid-connect/certs"