# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

annotations:
  category: Infrastructure
  licenses: Apache-2.0
  images: |
    - name: jmx-exporter
      image: docker.io/bitnami/jmx-exporter:1.0.1-debian-12-r6
    - name: kafka
      image: docker.io/bitnami/kafka:3.8.0-debian-12-r5
    - name: kubectl
      image: docker.io/bitnami/kubectl:1.31.1-debian-12-r2
    - name: os-shell
      image: docker.io/bitnami/os-shell:12-debian-12-r30
apiVersion: v2
appVersion: 3.8.0
dependencies:
- condition: zookeeper.enabled
  name: zookeeper
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 13.x.x
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  tags:
  - bitnami-common
  version: 2.x.x
description: Apache Kafka is a distributed streaming platform designed to build real-time pipelines and can be used as a message broker or as a replacement for a log aggregation solution for big data applications.
home: https://bitnami.com
icon: https://bitnami.com/assets/stacks/kafka/img/kafka-stack-220x234.png
keywords:
- kafka
- zookeeper
- streaming
- producer
- consumer
maintainers:
- name: Broadcom, Inc. All Rights Reserved.
  url: https://github.com/bitnami/charts
name: kafka
sources:
- https://github.com/bitnami/charts/tree/main/bitnami/kafka
version: 30.1.4
