deploymentName: account-deployment
serviceName: account
appLabel: account
appName: account

replicaCount: 1

image:
  repository: pisethbank/account
  tag: v3

containerPort: 8080

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

appname_enabled: true
profile_enabled: true
config_enabled: true
eureka_enabled: true
resouceserver_enabled: false
otel_enabled: true
kafka_enabled: true