# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

annotations:
  category: Analytics
  licenses: Apache-2.0
  images: |
    - name: grafana
      image: docker.io/bitnami/grafana:11.2.0-debian-12-r4
    - name: os-shell
      image: docker.io/bitnami/os-shell:12-debian-12-r30
apiVersion: v2
appVersion: 11.2.0
dependencies:
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  tags:
  - bitnami-common
  version: 2.x.x
description: Grafana is an open source metric analytics and visualization suite for visualizing time series data that supports various types of data sources.
home: https://bitnami.com
icon: https://bitnami.com/assets/stacks/grafana/img/grafana-stack-220x234.png
keywords:
- analytics
- monitoring
- metrics
- logs
maintainers:
- name: Broadcom, Inc. All Rights Reserved.
  url: https://github.com/bitnami/charts
name: grafana
sources:
- https://github.com/bitnami/charts/tree/main/bitnami/grafana
version: 11.3.20
