version: "3.8"
services:

  kafka:
    image: docker.io/bitnami/kafka:3.5
    container_name: kafka
    ports:
      - 9092:9092
    # volumes:
    #   - kafka_data:/bitnami
    environment:
      # KRaft settings
      KAFKA_CFG_NODE_ID: 0
      KAFKA_CFG_PROCESS_ROLES: controller,broker
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 0@kafka:9093
      # Listeners
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://:9092
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: PLAINTEXT
    extends:
      file: common.yml
      service: ms-deploy-network

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8082:8080
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    volumes:
      - /tmp/config.yml:/config.yml
    extends:
      file: common.yml
      service: ms-deploy-network

  postgres: 
    image: postgres:15   
    environment:
      # Environment Variables expecially for Postgres
      POSTGRES_DB: kdb
      POSTGRES_USER: kadmin
      POSTGRES_PASSWORD: kadmin
    healthcheck:
      test: "exit 0"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    extends:
      file: common.yml
      service: ms-deploy-network

  keycloak:
    image: quay.io/keycloak/keycloak:23.0.4
    container_name: keycloak
    ports:
      - "9080:8080"
    environment:
      KEYCLOAK_ADMIN: "admin"
      KEYCLOAK_ADMIN_PASSWORD: "admin"
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_DATABASE: kdb
      KC_DB_PASSWORD: kadmin
      KC_DB_USERNAME: kadmin
      KC_DB_SCHEMA: public
    command: "start-dev"
    depends_on:      
      postgres:
        condition: service_healthy
    extends:
      file: common.yml
      service: ms-deploy-network

  configserver:
    image: pisethbank/configserver:v2
    container_name: configserver-ms
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    ports:
      - "8071:8071"
    environment:
      SPRING_APPLICATION_NAME: "configserver"
      OTEL_SERVICE_NAME: "configserver"
    extends:
      file: common.yml
      service: ms-base
    

  eurekaserver:
    image: pisethbank/eurekaserver:v2
    container_name: eurekaserver-ms
    healthcheck:
      test: "curl --fail --silent localhost:9001/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    ports:
      - "9001:9001"
    environment:
      SPRING_APPLICATION_NAME: "eurekaserver"
      OTEL_SERVICE_NAME: "eurekaserver"
    extends:
      file: common.yml
      service: ms-base-configserver

  

  mongodb:
    image: mvertes/alpine-mongo:latest
    ports:
      - "7777:27017"
    volumes:
      - './data:/data/db'
    extends:
      file: common.yml
      service: ms-deploy-network

  account:
    image: pisethbank/account:v2
    container_name: account-ms
    healthcheck:
      test: "curl --fail --silent localhost:8080/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    environment:
      SPRING_APPLICATION_NAME: "account"
      OTEL_SERVICE_NAME: "account"
      #SPRING_RABBITMQ_HOST: rabbit
      SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS: "kafka:9092"
    # depends_on: 
    #   rabbit:
    #     condition: service_healthy
    extends:
      file: common.yml
      service: ms-base-eurekaserver

  card:
    image: pisethbank/card:v2
    container_name: card-ms
    healthcheck:
      test: "curl --fail --silent localhost:8070/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    ports:
      - "8070:8070"
    environment:
      MONGODB_HOST_NAME: mongodb
      SPRING_APPLICATION_NAME: "card"
      OTEL_SERVICE_NAME: "card"
    extends:
      file: common.yml
      service: ms-base-eurekaserver

  loan:
    image: pisethbank/loan:v2
    container_name: loan-ms
    healthcheck:
      test: "curl --fail --silent localhost:8090/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    ports:
      - "8090:8090"
    environment:
      MONGODB_HOST_NAME: mongodb
      SPRING_APPLICATION_NAME: "loan"
      OTEL_SERVICE_NAME: "loan"
    extends:
      file: common.yml
      service: ms-base-eurekaserver

  message:
    image: pisethbank/message:v2
    container_name: message-ms
    # depends_on:
    #   rabbit:
    #     condition: service_healthy
    environment:
      #SPRING_RABBITMQ_HOST: "rabbit"
      SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS: "kafka:9092"
    extends:
      file: common.yml
      service: ms-deploy-network

  gatewayserver:
    image: pisethbank/gatewayserver:v2
    container_name: gatewayserver-ms
    ports:
      - "8072:8072"
    depends_on: 
      account:
        condition: service_healthy
      card:
        condition: service_healthy
      loan:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "gatewayserver"
      OTEL_SERVICE_NAME: "gatewayserver"
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK-SET-URI: "http://keycloak:8080/realms/master/protocol/openid-connect/certs"  
    extends:
      file: common.yml
      service: ms-base-eurekaserver

networks:
  pisethbanknet: