version: "3.8"
services:
  rabbit:
    image: rabbitmq:3.12-management
    hostname: rabbitmq
    container_name: rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common.yml
      service: ms-deploy-network

  configserver:
    image: pisethbank/configserver:v2
    container_name: configserver-ms
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    ports:
      - "8071:8071"
    depends_on:
      rabbit:
        condition: service_healthy
    extends:
      file: common.yml
      service: ms-base

  eurekaserver:
    image: pisethbank/eurekaserver:v2
    container_name: eurekaserver-ms
    healthcheck:
      test: "curl --fail --silent localhost:9000/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    ports:
      - "9000:9000"
    extends:
      file: common.yml
      service: ms-base-configserver

  

  mongodb:
    image: mvertes/alpine-mongo:latest
    ports:
      - "7777:27017"
    volumes:
      - './data:/data/db'
    extends:
      file: common.yml
      service: ms-deploy-network

  account:
    image: pisethbank/account:v2
    container_name: account-ms
    ports:
      - "8080:8080"
    extends:
      file: common.yml
      service: ms-base-eurekaserver

  card:
    image: pisethbank/card:v2
    container_name: card-ms
    ports:
      - "8070:8070"
    environment:
      MONGODB_HOST_NAME: mongodb
    extends:
      file: common.yml
      service: ms-base-eurekaserver

  loan:
    image: pisethbank/loan:v2
    container_name: loan-ms
    ports:
      - "8090:8090"
    environment:
      MONGODB_HOST_NAME: mongodb
    extends:
      file: common.yml
      service: ms-base-eurekaserver

networks:
  pisethbanknet: